default: &default
  adapter: postgresql
  encoding: unicode
  url: postgres://backed_user:vc1gHT0RAGf66j3WFpdy5VK4T7T76Djb@dpg-cjua2knhdsdc73eb7llg-a/backed
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432
  username: backed_user
  password: vc1gHT0RAGf66j3WFpdy5VK4T7T76Djb

development:
  <<: *default
  database: backed

test:
  <<: *default
  database: backed

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>